import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalContextProvider from "@/context";
import AuthProvider from "@/auth-provider";
import { getServerSession } from "next-auth";
import NavBar from "@/components/common/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  // console.log("Session from layout", session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <GlobalContextProvider>
            <NavBar />
            {children}
          </GlobalContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
